# Generated by Django 4.2.16 on 2025-06-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='contact',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone2',
            field=models.CharField(default='09087654312', max_length=50),
            preserve_default=False,
        ),
    ]
