# Generated by Django 4.2.16 on 2025-07-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_supplier_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
