# Generated by Django 4.2.16 on 2025-09-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_markup_type', models.CharField(choices=[('percent', 'Percent'), ('absolute', 'Absolute')], default='percent', max_length=10)),
                ('default_markup_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_source', models.CharField(default='max_supply', max_length=20)),
            ],
        ),
    ]
