# Generated by Django 4.2.16 on 2025-06-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='item',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExpiryNotification',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='SalesDetail',
        ),
        migrations.DeleteModel(
            name='SalesInvoice',
        ),
    ]
