# Generated by Django 4.2.16 on 2025-07-07 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0004_remove_purchase_item_remove_purchase_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_bt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
