# Generated by Django 4.2.16 on 2025-07-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_created_bt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created_bt',
            new_name='created_by',
        ),
    ]
