# Generated by Django 4.2.16 on 2025-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_rename_created_bt_item_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_level',
            field=models.IntegerField(default=0),
        ),
    ]
