# Generated by Django 4.2.16 on 2025-07-25 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0009_brand_remove_item_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='cost_price',
            new_name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='date_supplied',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='manufacture_date',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='supply',
            name='supplied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supply',
            name='supply_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supply',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.brand'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
