# Generated by Django 4.2.16 on 2025-07-25 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_rename_cost_price_supply_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='items.item'),
        ),
    ]
