# Generated by Django 4.2.16 on 2025-07-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_supply_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='supplied_by',
            new_name='created_by',
        ),
    ]
