# Generated by Django 4.2.16 on 2025-07-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_rename_supplied_by_supply_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
