# Generated by Django 4.2.16 on 2025-08-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_alter_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='purchase_price',
            new_name='supply_price',
        ),
        migrations.AddField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
