# Generated by Django 4.2.16 on 2025-08-07 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_rename_purchase_price_supply_supply_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.AddField(
            model_name='brand',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
