# Generated by Django 4.2.16 on 2025-08-07 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_remove_item_barcode_remove_item_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 7, 8, 42, 40, 556560, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
