# Generated by Django 4.2.16 on 2025-08-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_alter_item_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='items.item'),
        ),
    ]
