# Generated by Django 4.2.16 on 2025-08-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_alter_brand_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='item',
        ),
        migrations.AlterField(
            model_name='supply',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='items.brand'),
            preserve_default=False,
        ),
    ]
