# Generated by Django 4.2.16 on 2025-06-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetail',
            old_name='invoice',
            new_name='sales',
        ),
    ]
