# Generated by Django 4.2.16 on 2025-06-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesinvoice_customer_salesinvoice_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdetail',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='total_price',
        ),
    ]
