# Generated by Django 4.2.16 on 2025-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_salesdetail_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdetail',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
