# Generated by Django 4.2.16 on 2025-06-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesdetail_brand_salesdetail_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetail',
            old_name='unit_price',
            new_name='price',
        ),
    ]
