# Generated by Django 4.2.16 on 2025-06-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_unit_price_salesdetail_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdetail',
            old_name='price',
            new_name='unit_price',
        ),
    ]
