# Generated by Django 4.2.16 on 2025-06-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_rename_price_salesdetail_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='user',
        ),
    ]
