# Generated by Django 4.2.16 on 2025-07-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesinvoice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('pos', 'POS'), ('transfer', 'Bank Transfer'), ('credit', 'Credit'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
