# Generated by Django 4.2.16 on 2025-07-25 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_supply_item'),
        ('sales', '0010_salesinvoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='items.item'),
        ),
    ]
