# Generated by Django 4.2.16 on 2025-08-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_salesdetail_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
