# Generated by Django 4.2.16 on 2025-08-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_remove_supply_item_alter_supply_brand'),
        ('sales', '0012_delete_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expirynotification',
            name='item',
        ),
        migrations.RemoveField(
            model_name='salesdetail',
            name='item',
        ),
        migrations.AddField(
            model_name='expirynotification',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='items.brand'),
        ),
    ]
